### ISSUE TITLE
yfont package doesn't find initals

### ISSUE THREAD

**Issue by FrankMittelbach** [TeX-Live/yinit#2]
The yfont package was/is the std way to access the various old German fonts by Yannis including the yinit initals.

However, it uses the yinitas versions as according to Walter Schmidt they fixed a number of bugs in the original yinit files. These driver files has now been moved to a different package (but are listed as obsolete on CTAN) and are not distributed by TeX Live any longer (only by MikTeX). As a result the yfonts package stopped working if used in a TL distribution.

Sample
```

\documentclass{article}
\usepackage{yfonts}

\begin{document}
\frakfamily\fraklines
\yinipar{D}ies: ist ein Blindtext an dem
sich verschiedene Dinge ablesen lassen. 
\end{document}
```

**Comment by norbusan** [comment]
Hallo Frank
yes I know, that is the case since about 2 or more years already.
The original yinit fonts couldn't be used with yfonts, due to metric errors. That is why the yinitas fonts were created. But unfortunately there is no license/copyright statement.

The recent changes I made with Yannis to the yinit fonts now make them work with yfonts.

Thanks fo reminding me. I have an updated yfonts package ready, but need to contact the original author (WAS?) - not sure if I get an answer and how to proceed. I just created https://github.com/TeX-Live/yfonts with the original package and the changes I made on top of it.

Any suggestion on how to proceed?

**Comment by FrankMittelbach** [comment]
Am 03.04.19 um 11:13 schrieb Norbert Preining:
> Thanks fo reminding me. I have an updated yfonts package ready, but need 
> to contact the original author (WAS?) - not sure if I get an answer and 
> how to proceed. I just created https://github.com/TeX-Live/yfonts with 
> the original package and the changes I made on top of it.
> 
> Any suggestion on how to proceed?
> 

I searched for Walter ... and as usual the email address in the readme's 
is dead :-(

But I guess his homepage so I will contact him. If the yinit fonts now 
work correctly then it is indeed best to have yfonts change to use the 
std ones (which seems trivial) basically replace yinitas again with yinit

If I can raise Walter we proceed from there, if not .. yfonts is LPPL so 
we could arrange for an update if the maintainer is not longer around, 
but I rather hope he will keep maintaining his work.

**Comment by norbusan** [comment]
Thanks, let me know how it proceeds!

**Comment by norbusan** [comment]
New version uploaded. Thanks Frank for contacting Walter.
